project:
  type: website
  output-dir: _site

website:
  title: "Anvil Benchmarks"
  navbar:
    left:
      - href: mlp.qmd
        text: MLP
    right:
      - icon: github
        href: https://github.com/r-xla/benchmarks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
